#!/usr/bin/env pwsh
# Build-time generator for VoiceWink's Sentry crash-reporting DSN.
#
# Reads the Sentry DSN from a GITIGNORED file (installer/.sentry-dsn) and, ONLY when
# -Embed "true" is passed (i.e. a signed release build via installer/release-update.*),
# bakes it into a compiled constant. Dev / CI / Debug builds pass no -Embed flag, so the
# DSN is EMPTY and crash reporting stays inert there (SentryInitializer resolves an empty
# EmbeddedDsn -> TryInit returns false even with opt-in). That empty-in-dev behavior is
# also what keeps SentryInitializerTests.IsInitialized_Initial_IsFalse green.
#
# The DSN is NEVER passed on the command line (only read from the file), so it can't leak
# into process args / build logs. The generated file lands in obj/ (gitignored), so the DSN
# is never committed.
#
# Invoked from VoiceWink.csproj's GenerateSentryConfig target before every compile pass.
#
# ASCII-ONLY: MSBuild's <Exec> runs this under Windows PowerShell 5.1, which reads a
# UTF-8-no-BOM .ps1 in the legacy codepage. A non-ASCII char (em-dash, arrow) would mangle
# and can break the parse. Keep this file ASCII; the user-invoked release-update.* scripts
# run under pwsh/bash.
[CmdletBinding()]
param(
    [string]$Embed = "",
    [string]$DsnFile = "",
    [Parameter(Mandatory = $true)][string]$OutFile
)

$ErrorActionPreference = 'Stop'

$dsn = ""

# Only embed when this is a release build (-Embed "true") AND the gitignored DSN file exists.
# Dev/Debug/CI builds pass no -Embed, so they never bake the DSN even if the file is present
# - keeping the un-gated dev build credential-free and the test suite's no-DSN assertion valid.
if ($Embed -eq 'true' -and $DsnFile -and (Test-Path -LiteralPath $DsnFile)) {
    foreach ($line in Get-Content -LiteralPath $DsnFile) {
        if ($line -match '^\s*SENTRY_DSN\s*=\s*(.+?)\s*$') { $dsn = $Matches[1] }
    }
}

# Tolerate values wrapped in single or double quotes in the file.
function Remove-WrappingQuotes([string]$v) {
    if ($v.Length -ge 2 -and (($v[0] -eq '"' -and $v[-1] -eq '"') -or ($v[0] -eq "'" -and $v[-1] -eq "'"))) {
        return $v.Substring(1, $v.Length - 2)
    }
    return $v
}
# Trim so a whitespace-only value collapses to empty (inert) rather than baking a blank DSN.
$dsn = (Remove-WrappingQuotes $dsn).Trim()

# Fail fast on a malformed DSN. A whitespace/control char would compile into the constant and
# then make SentrySdk.Init throw at runtime; a non-DSN string would silently mis-route events.
# A Sentry DSN is a URL of the shape https://<key>@<host>/<projectId> with no whitespace.
if ($dsn) {
    if ($dsn -match '[\s\x00-\x1F\x7F]') {
        throw "generate-sentry-config: SENTRY_DSN contains whitespace or a control character - fix installer/.sentry-dsn."
    }
    if ($dsn -notmatch '^https://[^@/\s]+@[^/\s]+/[0-9]+$') {
        throw "generate-sentry-config: SENTRY_DSN is not a valid Sentry DSN (expected https://<key>@<host>/<projectId>); fix installer/.sentry-dsn."
    }
}

# Escape for a C# verbatim string literal (@"..."): only the double-quote needs doubling.
function ConvertTo-CSharpVerbatim([string]$s) { return ($s -replace '"', '""') }

$content = @"
// <auto-generated/> Build-time Sentry config.
// Generated by scripts/generate-sentry-config.ps1 on each build. DO NOT EDIT or commit.
// The DSN is read from a gitignored file at build time and embedded ONLY for signed release
// builds (-Embed true); empty in dev/CI builds, so crash reporting stays inert there.
namespace VoiceWink.Services.System;

internal static class SentryConfig
{
    /// <summary>The Sentry DSN baked into signed release builds; empty in dev/CI builds.</summary>
    public const string EmbeddedDsn = @"$(ConvertTo-CSharpVerbatim $dsn)";
}
"@

$dir = Split-Path -Parent $OutFile
if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

# Write only when the (newline-normalised) content changed, so we don't churn the file's
# timestamp and force an unnecessary recompile on every incremental build.
$existing = if (Test-Path -LiteralPath $OutFile) { Get-Content -LiteralPath $OutFile -Raw } else { $null }
$normExisting = if ($null -ne $existing) { $existing -replace "`r`n", "`n" } else { $null }
$normContent = $content -replace "`r`n", "`n"
if ($normExisting -ne $normContent) {
    Set-Content -LiteralPath $OutFile -Value $content -Encoding UTF8 -NoNewline
}
