namespace VoiceWink.Services.AIEnhancement;

/// <summary>
/// The materialized reference image handed to the provider clients (ENH-6): raw file
/// bytes plus the ACCURATE mime type derived from the file extension
/// (<c>ReferenceImagePolicy.MimeFromExtension</c> — png/jpeg/webp whitelist, never a
/// defaulted "image/png" for foreign bytes). Produced exclusively by
/// <c>AIEnhancementService.ReadReferenceImageAsync</c>, which owns validation, the
/// size cap, and the no-path-in-errors rule.
/// </summary>
public sealed record ReferenceImage(byte[] Bytes, string MimeType);

/// <summary>
/// Thrown when a selected reference image can no longer be used (deleted, moved,
/// failed containment re-validation). A dedicated type — not message sniffing — so
/// the redo re-arm path can DROP the reference from the re-armed context (otherwise
/// a deleted file would fail every subsequent redo identically), while transient
/// provider failures keep it. Message carries NO path text (Browse paths must not
/// leak into logs/Sentry breadcrumbs). Sanitation rule for the BASE type (ENH-6f):
/// drop the WHOLE re-armed list — correct for the count/aggregate-cap throws, which
/// indict the selection as a whole; per-item failures use the
/// <see cref="ReferenceImagesUnavailableException"/> subtype instead.
/// </summary>
public class ReferenceImageUnavailableException : InvalidOperationException
{
    public ReferenceImageUnavailableException(string message) : base(message) { }
}

/// <summary>
/// ENH-6f: one or more items of a multi-reference read failed VALIDATION while others
/// may be fine. Failure identity is INDEX-based (positions in the selection list the
/// read was given — stable because carriers are immutable snapshots), deliberately not
/// path- or equality-based: duplicates stay distinguishable and NO path ever rides the
/// exception (Codex plan round 1). Re-arm sanitation drops exactly these indices.
/// </summary>
public sealed class ReferenceImagesUnavailableException : ReferenceImageUnavailableException
{
    public IReadOnlyList<int> FailedIndices { get; }

    public ReferenceImagesUnavailableException(string message, IReadOnlyList<int> failedIndices)
        : base(message)
    {
        FailedIndices = failedIndices;
    }
}

/// <summary>
/// ENH-6f: the AGGREGATE byte budget (<c>ReferenceImagePolicy.MaxTotalBytes</c>) was
/// exceeded — thrown BEFORE the offending allocation, never collected as a per-item
/// failure (the budget indicts the selection as a whole; base-type sanitation drops
/// the full list). Defense-in-depth: the dialog enforces the same budget at add time.
/// </summary>
public sealed class ReferenceImageBudgetExceededException : ReferenceImageUnavailableException
{
    public ReferenceImageBudgetExceededException(string message) : base(message) { }
}

/// <summary>
/// Result of an image generation (ENH-6b): the generated bytes plus the ALREADY
/// VALIDATED reference bytes+mime that were actually sent, in selection order (empty
/// when the run had no references — ENH-6f made this plural). The service deliberately
/// returns the in-memory references instead of persisted paths — retention is owned by
/// the history-aware orchestration (<c>ReferencePersistence.PersistWithRowAsync</c>),
/// which copies to disk only for history-enabled runs: successful ones from these bytes
/// (re-reading the originals after the provider call would reopen the TOCTOU window the
/// read-time validation closed), and FAILED ones via a fresh validated read (ENH-6c —
/// this record never materializes on the throw path).
/// <c>Effective</c> (IMG-2, MANDATORY — an optional slot would create an invalid
/// success state): the per-model-normalized options the request ACTUALLY used; the
/// success paths persist History labels and re-arm redo from it, never from the prompt.
/// </summary>
public sealed record ImageGenerationResult(
    byte[] ImageBytes,
    IReadOnlyList<ReferenceImage> UsedReferences,
    Helpers.EffectiveImageOptions Effective)
{
    /// <summary>
    /// What <see cref="ImageBytes"/> ACTUALLY is, classified once at the receipt boundary so the
    /// saver names the file truthfully instead of assuming PNG (riverflow returns WebP).
    ///
    /// <para><b>Non-positional and internal on purpose.</b> This record is public while
    /// <see cref="Helpers.ImageBytesKind"/> is internal, so a positional public parameter of an
    /// internal type would not compile; an internal init property is legal here and keeps the public
    /// surface unchanged — this type is public only because it rides the public service API, not
    /// because anything outside the assembly consumes it.</para>
    /// </summary>
    internal Helpers.ImageBytesKind Kind { get; init; } = Helpers.ImageBytesKind.Unknown;
}
